name: SQS Automation Docker Build and Push

on:
  push:
    branches:
      - main
  workflow_dispatch:      # Allows manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    environment: dev
    
    steps:
      - uses: actions/checkout@v4 #checkout repository

      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-code-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'
          security-checks: 'vuln,secret,config'

      - name: Upload FS/code Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-code-results.sarif'

      - name: Run Trivy dockerfile scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-config-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'

      - name: Upload Config Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-config-results.sarif'
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sqs-automation:latest