name: Daily SQS Automation Docker Run

permissions:
  id-token: write
  contents: read


on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC daily - 2:00 AM Israel Time
  workflow_dispatch:      # Allows manual trigger

jobs:
  run-container:
    runs-on: ubuntu-24.04
    environment: dev
    env:
      ACTIONS_STEP_DEBUG: true
    steps:
      - name: Configure AWS Credentials for region audience
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: ${{ vars.DEFAULT_REGION}}
          role-to-assume: ${{ vars.IAM_GITHUB_ACTIONS_ROLE}}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Pull Docker image
        run: |
          docker pull hadarneu/sqs-automation:latest

      - name: Manual Trivy Setup
        uses: aquasecurity/setup-trivy@v0.2.0
        with:
          cache: true
          version: v0.57.1

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: 'hadarneu/sqs-automation:latest'
          format: 'json'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          scan-type: 'image'
          output: 'trivy.json'

      - name: Run Docker container
        run: |
          docker run -e AWS_ACCESS_KEY_ID=${{ env.AWS_ACCESS_KEY_ID }} \
                    -e AWS_SECRET_ACCESS_KEY=${{ env.AWS_SECRET_ACCESS_KEY }} \
                    -e AWS_SESSION_TOKEN=${{ env.AWS_SESSION_TOKEN }} \
                    -e AWS_DEFAULT_REGION=${{ env.AWS_DEFAULT_REGION }} \
                    -e S3_BUCKET=${{ vars.S3_BUCKET }} \
                    -e FILE_PATH=${{ vars.FILE_PATH }} \
                    -e LOG_MODE=${{ vars.LOG_MODE }} \
                    hadarneu/sqs-automation:latest

      - name: Handle potential failures
        if: failure()
        run: |
          echo "Container run failed"
          exit 1