name: Daily Docker Run

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC daily - 2:00 AM Israel Time
  workflow_dispatch:      # Allows manual trigger

jobs:
  run-container:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull and run Docker image
        run: |
          docker pull sqs-automation:latest
          docker run sqs-automation:latest

      - name: Handle potential failures
        if: failure()
        run: |
          echo "Container run failed"
          exit 1