name: Daily Docker Run

permissions:
  id-token: write
  contents: read


on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC daily - 2:00 AM Israel Time
  workflow_dispatch:      # Allows manual trigger

jobs:
  run-container:
    runs-on: ubuntu-latest
    environment: dev
    env:
      ACTIONS_STEP_DEBUG: true
    steps:
      - name: Configure AWS Credentials for region audience
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: ${{ vars.DEFAULT_REGION}}
          role-to-assume: ${{ vars.IAM_GITHUB_ACTIONS_ROLE}}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Pull and run Docker image
        run: |
          docker pull hadarneu/sqs-automation:latest
          docker run --env-file environment_vars hadarneu/sqs-automation:latest 


      - name: Handle potential failures
        if: failure()
        run: |
          echo "Container run failed"
          exit 1